accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view, name='login'),
    path('logout/',views.logout_view, name='logout')
]

articles/urls.py
from django.urls import path

from articles import views

app_name = 'articles'

urlpatterns = [
    path('',views.article_list, name='list'),
    path('create',views.article_create,name='create'),
    path("<slug:slug>",views.article_item, name='article_detail'),
    path("update/<slug:slug>",views.article_update, name='update'),
    path("delete/<slug:slug>",views.article_delete,name='delete')
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite import views
from articles import views as article_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',article_view.article_list, name='homepage'),
    path('about/',views.about, name='about'),
    path('articles/', include('articles.urls')),
    path('accounts/',include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.contrib.auth.models import User
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:50] + "..."

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth import password_validation

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus":True, "class":"form-control mb-3"}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete":"current-password", "class":"form-control mb-3"}),
    )

class SignupForm(UserCreationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus":True, "class":"form-control mb-3"}))
    password1 = forms.CharField(
        label="Password",
        required=True,
        widget=forms.PasswordInput(attrs={"autocomplete":"new-password","class":"form-control mb-3"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control mb-3"}),
        help_text="Enter the same password as before, for verification"
    )

articles/forms.py
from django import forms

from . import models

class ArticleForm(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title", "body", "thumbnail"]
        widgets = {
            "title": forms.TextInput(attrs={
                "placeholder": "Write article title",
                "class": "form-control mb-3"
            }),
            "body": forms.Textarea(attrs={
                "placeholder": "Write article text",
                "class": "form-control mb-3"
            }),
            "thumbnail": forms.ClearableFileInput(attrs={
                "class": "form-control-file mb-3"
            }),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login,logout
from accounts.forms import LoginForm, SignupForm
from django.http import HttpResponseRedirect

def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('homepage')
    else:
        form = SignupForm()
    return render(request,'accounts/signup.html', {"form":form})

def login_view(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('homepage')
    else:
        form = LoginForm()
    return render(request,'accounts/login.html',{"form":form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
    return redirect('homepage')

articles/views.py
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
from django.shortcuts import render, redirect
from articles.models import Article
from . import forms

def article_list(request):
    articles= Article.objects.all().order_by('date')
    return render(request,"articles/article_list.html",{'articles':articles})

def article_item(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request,"articles/article_item.html",{"article":article})

@login_required(login_url='accounts:login')
def article_create(request):
    if request.method=="POST":
        form = forms.ArticleForm(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('homepage')
    else:
        form = forms.ArticleForm()
    return render(request, 'articles/article_form.html', {'form':form})

@login_required(login_url='accounts:login')
def article_update(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user.id == article.author.id:
        if request.method == 'POST':
            form = forms.ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                instance.save()
                return redirect('articles:article_detail',slug=article.slug)
        else:
            form = forms.ArticleForm(instance=article)
        return render(request,'articles/article_form.html',{"form":form})
    return HttpResponse('401 Unauthorized', status=401)

@login_required(login_url='accounts:login')
def article_delete(request,slug):
    article = Article.objects.get(slug=slug)
    if request.user.id == article.author.id:
        if request.method == 'POST':
            article.delete()
            return redirect('homepage')
        return render(request,'articles/article_confirm_delete.html',{'article':article})
    return HttpResponse('401 Unauthorized', status=401)

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request,'homepage.html')

def about(request):
    return render(request,'about.html')

accounts/templates/accounts/login.html
{% extends "base_layout.html" %}
{%block title%}Accounts{% endblock title %}
{% block content %}
<h1>Signup</h1>
<form class="form" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <button type="submit">Login</button>
</form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base_layout.html" %}
{%block title%}Accounts{% endblock title %}
{% block content %}
<h1>Signup</h1>
<form class="form" action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Sign Up</button>
</form>
{% endblock content %}

articles/templates/articles/article_confirm_delete.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %}{{ article.title }}{% endblock title %}
{% block content %}
    <div class="article-confirm-delete">
        <h1 class="mb-3">Are you sure?</h1>
        <form class="form" method="POST">
            {% csrf_token %}
            {{form}}
            <button type="submit" class="btn btn-danget">Yes</button>
            <a href="{% url 'homepage' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock content %}

articles/templates/articles/article_form.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %}Create or update Article{% endblock title %}
{% block content %}
    <h1>Create or update Article</h1>
    <form class="form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {{form}}
    <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock content %}

articles/templates/articles/article_item.html
{% extends "base_layout.html" %}
{% block title %}{{article.title}}{% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="article_detail">
        <img src="{{ article.thumbnail.url }}">
        <h1>{{article.title}}</h1>
        <p>{{article.body}}</p>
        {% if user.is_authenticated and user.id == article.author.id %}
            <div>
                <a class="btn btn-warning"
                    href="{% url 'articles:update' slug=article.slug %}">
                    Update
                </a>
                <a class="btn btn-danger"
                    href="{% url 'articles:delete' slug=article.slug %}">
                </a>
            </div>
        {% endif %}
    </div>
</div>

{% endblock content %}

articles/templates/articles/article_list.html
{% extends "base_layout.html" %}
{% block title %}Article List{% endblock title %}
{% block content %}
<div class="container-fluid">
    <h1 class="article_list-h1">Article list</h1>
    <div class="row article_list-row">
        {% for element in articles %}
            <div class="article__item col-4">
                <h2>
                    <a href="{% url 'articles:article_detail' slug=element.slug %}">
                        {{element.title}}
                    </a>
                </h2>
                <p>
                    {{element.snippet}}
                </p>
                <time>
                    {{element.date}}
                </time>
            </div>
        {% endfor %}
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}" class="article_list_create-btn">
        Create article
    </a>
    {% endif %}
</div>
{% endblock content %}

templates/about.html
{% extends "base_layout.html" %}
{% block content %}
<div class="container-fluid">
    <h1>About us</h1>
</div>
{% endblock content %}

templates/base_layout.html
{% load static %}
<!DOCTYPE>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Default title{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
</head>
<body>
<header>
    <div class="container-fluid">
        <div class="header__wrapper">
            <a href="{% url 'homepage' %}">
                LOGO
            </a>
            <a href="{% url 'about' %}">
                About
            </a>
            {% if user.is_authenticated %}
             <a href="{% url 'homepage' %}">
                Articles
            </a>
            <form class="form" action="{% url 'accounts:logout' %}" method="POST">
                {%csrf_token%}
                <button type="submit">Logout</button>
            </form>
            {% else %}
                <a href="{% url 'accounts:signup' %}">Sign Up</a>
                <a href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
        </div>

    </div>
</header>
{% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/homepage.html
{% extends "base_layout.html" %}
{% block content %}
<div class="container-fluid">
    <h1>Homepage</h1>
</div>
{% endblock content %}